[build]
  command = "next build"
  publish = ".next" # Ensures Netlify serves the Next.js output

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/admin/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-store"

[dev]
  command = "next dev"
  port = 8888 # Customize if needed
  targetPort = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"
